/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Macx' at '17-5-10 上午10:38' with Gradle 3.2
 *
 * @author Macx, @date 17-5-10 上午10:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
